### ISSUE TITLE
Problem with PayPal

### ISSUE THREAD

**Issue by Kaputz** [to-bai/magento2-geo-store-switcher#12]
Hello,
I am trying to integrate this on a store with 2 views, one for a specific country and another for all the others.
The extension is super easy to setup and it works flawlessly. It is exactly what I needed.

It does however break the default PayPal module somehow, and I can't figure out why. 
I'm working with Magento 2.2.5, 1 website (default), 1 store (default) 2 store views. Breaks in both views aswell.

Can you please verify if you can replicate this behavior?

**Comment by ytorbyk** [comment]
HI @Kaputz 
What exactly is broken in PayPal module?

**Comment by Kaputz** [comment]
When I try to checkout directly with paypal it doesn't redirect me to paypal website. 
Instead I'm redirected to my cart and i get the message "We can't initialize Express Checkout."
If i go through the whole checkout step on magento and then select to pay with paypal, the paypal window pops up (as it should) but then it shuts down and I'm redirected back to the payment page.
I'm still not 100% sure the problem is caused by ONLY your extension (still running some tests), but on my production store it seems that the trigger is in fact this extension as when i disable it the paypal starts working as intended.

**Comment by to8gal** [comment]
Hello, is this issue been solved?

**Comment by Kaputz** [comment]
Hello,
Yes, the issue has been solved.
Wasn't a problem with this module after all.
Thank you.
